[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

# 这个重定向可以保留，但我们前端代码现在会直接使用/.netlify/functions/api路径
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# 确保所有的路由请求都被处理
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api"
  # 这里不需要添加敏感变量，请在Netlify控制台中添加API_KEY和API_URL
  # 关闭机密扫描
  SECRETS_SCAN_ENABLED = "false" 